---
- name: install postgresql
  apt:
    update_cache: yes
    name: ['postgresql', 'python-psycopg2']
    state: latest

- name: create db
  become: yes
  become_user: postgres
  postgresql_db:
    name: main
- name: add_user
  become: yes
  become_user: postgres
  postgresql_user:
    db: main
    user: dd
    password: '12345'
- name: enable postgresql and start
  become: yes
  become_user: postgres
  systemd:
    name: postgresql
    state: started
    enabled: yes
