---
- hosts: jenkins
  vars:
    java_installer: java_apt_install
  remote_user: root
  gather_facts: false

  roles:
    # - "{{ java_installer }}"
    # - tomcat_install
    - jenkins_install
    - jobinsert_role
