---
- hosts: liferay
  vars:
    java_installer: java_apt_install
  remote_user: root
  gather_facts: false

  roles:
    - "{{ java_installer }}"
    - wildfly_install
    # - liferay_download_files
    # - liferay_install
    # - liferay_deploy
