---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
    java_installer: java_apt_install
  remote_user: root

  roles:
    - "{{ java_installer }}"
    - wildfly_install
    - liferay_download_files
    - liferay_install
    - liferay_deploy
