---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    # - name: Replacement to <any-address\>
    #   lineinfile:
    #     path: /opt/wildfly-11.0.0.Final/standalone/configuration/standalone.xml
    #     line: '<any-address/>'
    #     regexp: '^            <inet-address value="${jboss.bind.address.management:127.0.0.1}"/>'
    # - name: Replacement to <any-address\>
    #   lineinfile:
    #     path: /opt/wildfly-11.0.0.Final/standalone/configuration/standalone.xml
    #     line: '<any-address/>'
    #     regexp: '^<inet-address value="${jboss.bind.address:127.0.0.1}"/>'
    #     insertbefore: BOF
    # - name: test3
    #   xml:
    #     path: /opt/wildfly-11.0.0.Final/standalone/configuration/standalone.xml
    #     xpath: /server
    #     set_children:
    #     - children: any-address
    - name: test config
      lineinfile:
        path: /opt/wildfly-11.0.0.Final/standalone/configuration/standalone.xml
        regexp: '<inet-address'
        line: '            <any-address/>'
    - name: Start WildFly
      command: /opt/wildfly-11.0.0.Final/bin/./standalone.sh
