---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    - name: Replacement to <any-address\>
      lineinfile:
        path: /opt/wildfly-11.0.0.Final/standalone/configuration/standalone.xml
        line: '<any-address/>'
        regexp: '^<inet-address value="${jboss.bind.address.management:127.0.0.1}"/>'
        insertbefore: BOF
    - name: Replacement to <any-address\>
      lineinfile:
        path: /opt/wildfly-11.0.0.Final/standalone/configuration/standalone.xml
        line: '<any-address/>'
        regexp: '^<inet-address value="${jboss.bind.address:0.0.0.0}"/>'
        insertbefore: BOF
