---
# tasks file for plugins_install
- name: Install jenkins-cli.jar
  get_url:
    url: "http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/jnlpJars/jenkins-cli.jar"
    dest: "{{jenkins_path}}"

- name: Add User admin to jenkins
  shell: echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("admin","admin")' | java -jar {{jenkins_path}}/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/ groovy =

- name: Restart tomcat
  systemd:
    state: restarted
    name: tomcat

- name: Wait for tomcat to come up
  uri:
    url: "http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 200
  delay: 5

- name: Wait for Jenkins
  pause:
      seconds: 90

- name: Install jenkins plugins
  #shell: "java -jar {{jenkins_path}}/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/ install-plugin {{ item }}"
  jenkins_plugin:
    name: "{{ item }}"
    url: "http://127.0.0.1:8080/jenkins"
    timeout: 1000
  loop:
    - ws-cleanup # Workspace Cleanup
    - workflow-aggregator # Pipeline
    - pipeline-stage-view # Pipeline: Stage View
    - git # Git
    - ansible # Ansible
    - ansicolor # AnsiColor

- name: Restart tomcat
  systemd:
    state: restarted
    name: tomcat

- name: Wait for Tomcat to come up
  uri:
    url: "http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 200
  delay: 5

- name: Add job to jenkins
  shell: "java -jar /root/.jenkins/jenkins-cli.jar -s http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/ create-job netcracker < /root/Netcrecker-project/export.xml"

- name: Start pipeline
  shell: curl http://{{jenkins_ip_external}}:{{jenkins_port}}/jenkins/job/{{job_name}}/build?token=START_PIPELINE
