---

- name: Create folder /opt/wildfly/modules/com/liferay/portal/main
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/wildfly/modules
    - /opt/wildfly/modules/com
    - /opt/wildfly/modules/com/liferay
    - /opt/wildfly/modules/com/liferay/portal
    - /opt/wildfly/modules/com/liferay/portal/main
- name: Remove all files
  shell: rm -rf /opt/wildfly/modules/com/liferay/portal/main/*
- name: Unzip dependences
  shell: unzip ~/liferay/liferay-ce-portal-dependencies*.zip -d /opt/wildfly/modules/com/liferay/portal/main
  # unarchive:
  #   src: "~/liferay/liferay-ce-portal-dependencies-7.2.0-ga1-20190531153709761.zip"  #TODO: create global variable
  #   dest: "/opt/wildfly/modules/com/liferay/portal/main"
- name: Move dependences to main
  shell: mv /opt/wildfly/modules/com/liferay/portal/main/l*/* /opt/wildfly/modules/com/liferay/portal/main && rmdir /opt/wildfly/modules/com/liferay/portal/main/liferay-ce-portal-dependencies-7.2.0-ga1
- name: Create module.xml files
  lineinfile:
    create: true
    path: /opt/wildfly/modules/com/liferay/portal/main/module.xml
    line: "{{ item }}"
  with_items:
    "{{ module_xml_list }}"
- name: Unzip OSGi
  shell: rm -rf /opt/osgi/* && unzip ~/liferay/liferay-ce-portal-osgi-*.zip -d /opt/osgi
- name: Move osgi to osgi
  shell: mv /opt/osgi/liferay-ce-portal-osgi-7.2.0-ga1/* /opt/osgi && rm -rf /opt/osgi/liferay-ce-portal-osgi-*
- name: Modify standalone.xml
  template:
    src: standalone_tmplt.j2
    dest: /opt/wildfly/standalone/configuration/standalone.xml
  vars:
    filter_spec: '<filter-spec value="not(any(match(&quot;WFLYSRV0059&quot;),match(&quot;WFLYEE0007&quot;)))" />'
    deployment_timeout: 'deployment-timeout="600"'
    jsp_config: '<jsp-config development="true" source-vm="1.8" target-vm="1.8" />'
- name: Delete all old undertow jars
  chdir: "{{ item }}"
  shell: "rm undertow*"
  with_items:
    - /opt/wildfly/modules/system/layers/base/io/undertow/websocket/main
    - /opt/wildfly/modules/system/layers/base/io/undertow/servlet/main
    - /opt/wildfly/modules/system/layers/base/io/undertow/core/main
- name: Copy new undertow jars
  chdir: "/opt/wildfly/modules/system/layers/base/io/undertow/{{ item }}/main"
  shell: "cp {{ undertow_download_path }}/undertow/undertow-{{ item }}* ./"
  with_items:
    - websocket
    - servlet
    - core
- name: Edit module.xml
  chdir: "/opt/wildfly/modules/system/layers/base/io/undertow/{{ item }}/main"
  lineinfile:
    path: main.xml
    regexp: "<resource-root path="
    line: '<resource-root path="undertow-websockets-jsr-2.0.23.Final.jar"/>'
  with_items:
    - websocket
    - servlet
    - core
