- name: Download Liferay dependences
  get_url:
    url: https://sourceforge.net/projects/lportal/files/Liferay%20Portal/7.2.0%20GA1/liferay-ce-portal-dependencies-7.2.0-ga1-20190531153709761.zip/download
    dest: '~'
- name: Download OSGI zip file
  get_url:
    url: https://sourceforge.net/projects/lportal/files/Liferay%20Portal/7.2.0%20GA1/liferay-ce-portal-osgi-7.2.0-ga1-20190531153709761.zip/download
    dest: '~'
- name: Download Liferay portal
  get_url:
    url: https://sourceforge.net/projects/lportal/files/Liferay%20Portal/7.2.0%20GA1/liferay-ce-portal-7.2.0-ga1-20190531153709761.war/download
    dest: '~'
- name: Create directory for Undertow jars
  file:
    path: '~/undertow'
    state: directory
- name: Download Undertow websocket jar
  get_url:
    url: https://repo1.maven.org/maven2/io/undertow/undertow-websockets-jsr/2.0.23.Final/undertow-websockets-jsr-2.0.23.Final.jar
    dest: '~/undertow'
- name: Download Undertow servlet jar
  get_url:
    url: https://repo1.maven.org/maven2/io/undertow/undertow-servlet/2.0.23.Final/undertow-servlet-2.0.23.Final.jar
    dest: '~/undertow'
- name: Download Undertow core jar
  get_url:
    url: https://repo1.maven.org/maven2/io/undertow/undertow-core/2.0.23.Final/undertow-core-2.0.23.Final.jar
    dest: '~/undertow'
