---

- name: Download & Unzip WildFly
  unarchive:
    remote_src: yes
    src: https://download.jboss.org/wildfly/17.0.1.Final/wildfly-17.0.1.Final.tar.gz
    dest: /opt
- name: Create a symbolic link
  file:
    src: /opt/wildfly-17.0.1.Final
    dest: /opt/wildfly
    state: link
- name: Replacement to <any-address\> [1]
  lineinfile:
    path: /opt/wildfly/standalone/configuration/standalone.xml
    regexp: '<inet-address'
    line: '            <any-address/>'
- name: Replacement to <any-address\> [2]
  lineinfile:
    path: /opt/wildfly/standalone/configuration/standalone.xml
    regexp: '<inet-address'
    line: '            <any-address/>'
- name: Add admin user to WildFly
  shell: /opt/wildfly/bin/add-user.sh root toor
