---

- name: Download & Unzip WildFly
  unarchive:
    remote_src: yes
    src: https://download.jboss.org/wildfly/17.0.1.Final/wildfly-17.0.1.Final.tar.gz
    dest: /opt
- name: Create a symbolic link
  file:
    src: /opt/wildfly-17.0.1.Final
    dest: /opt/wildfly
    state: link
- name: Replacement to <any-address\> [1]
  lineinfile:
    path: /opt/wildfly/standalone/configuration/standalone.xml
    regexp: '<inet-address'
    line: '            <any-address/>'
- name: Replacement to <any-address\> [2]
  lineinfile:
    path: /opt/wildfly/standalone/configuration/standalone.xml
    regexp: '<inet-address'
    line: '            <any-address/>'
# - name: Start WildFly # -- comment to pull updates ---
#   command: systemctl start wildfly
# - name: Status of WildFly
#   command: systemctl status wildfly
# - name: Create a directory for conf FILE
#   file:
#     path: /etc/wildfly
#     state: directory
# - name: Copy config
#   copy:
#     src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
#     dest: /etc/wildfly
#     remote_src: yes
# - name: Create a directory for launch.sh FILE
#   file:
#     path: /etc/wildfly/bin
#     state: directory
# - name: Copy start script
#   copy:
#     src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
#     dest: /opt/wildfly/bin
#     remote_src: yes
# - name: Change exec acess to .sh files
#   command: sh -c 'chmod +x /opt/wildfly/bin/*.sh'
# - name: Copy .service unit
#   copy:
#     src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
#     dest: /etc/systemd/system/
#     remote_src: yes
# - name: restart demon services
#   command: systemctl daemon-reload
# - name: Start WildFly
#   command: systemctl start wildfly
# - name: Status of WildFly
#   command: systemctl status wildfly
