---

# - name: Download java
#   get_url:
#     url: https://download.oracle.com/otn/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-arm32-vfp-hflt.tar.gz
#     headers:
#       Cookie: oraclelicense=accept-securebackup-cookie
#     validate_certs: no
#     dest: '~'
vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"


- name: Download Java
  command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"


- name: Create directory for java
  file:
    path: /usr/lib/jvm
    state: directory
- name: Unarchive java
  unarchive:
    src: ~/jdk-13_linux-x64_bin.tar.gz
    dest: /usr/lib/jvm
- name: Add Java to $PATH
  command: echo ${PATH}:/usr/lib/jvm/jdk-13/bin > /etc/environment
- name: Add $JAVA_HOME to environment
  command: 'echo JAVA_HOME="/usr/lib/jvm/jdk-13" >> /etc/environment'
- name: Inform UBUNTU about Java location [1]
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jdk-13/bin/java
- name: Inform UBUNTU about Java location [2]
  alternatives:
    link: /usr/bin/javac
    name: javac
    path: /usr/lib/jvm/jdk-13/bin/javac
- name: Inform UBUNTU about Java location [3]
  alternatives:
    name: java
    path: /usr/lib/jvm/jdk-13/bin/java
- name: Inform UBUNTU about Java location [4]
  alternatives:
    name: javac
    path: /usr/lib/jvm/jdk-13/bin/javac
