---

- name: Download java
  get_url:
    url: {{ download_url }}
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie
    validate_certs: no
    dest: {{ download_folder }}
- name: Create directory for java
  file:
    path: {{ java_name }}
    state: directory
- name: Unarchive java
  unarchive:
    src: {{ java_archive }}
    dest: /usr/lib/jvm
- name: Add Java to $PATH
  command: echo ${PATH}:/usr/lib/jvm/jdk-13/bin > /etc/environment
- name: Add $JAVA_HOME to environment
  command: 'echo JAVA_HOME="/usr/lib/jvm/jdk-13" >> /etc/environment'
- name: Inform UBUNTU about Java location [1]
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jdk-13/bin/java
- name: Inform UBUNTU about Java location [2]
  alternatives:
    link: /usr/bin/javac
    name: javac
    path: /usr/lib/jvm/jdk-13/bin/javac
- name: Inform UBUNTU about Java location [3]
  alternatives:
    name: java
    path: /usr/lib/jvm/jdk-13/bin/java
- name: Inform UBUNTU about Java location [4]
  alternatives:
    name: javac
    path: /usr/lib/jvm/jdk-13/bin/javac
