---
- name: Download Jenkins
  get_url:
    src: http://mirrors.jenkins.io/war/latest/jenkins.war
    dest: /opt/tomcat/lastest/webapps/
- name: Fix AWT error - apt ttf-dejavu & fontconfig
  apt:
    update_cache: yes
    name: ['ttf-dejavu', 'fontconfig']
