---
- name: Cleaning from previous versions
  file:
    path: "/opt/{{ item }}"
    state: absent
  loop:
    - apache-tomcat-*
    - tomcat

- name: Create new group tomcat
  group:
    name: tomcat
    state: present

- name: Create new user tomcat
  user:
    name: tomcat
    group: tomcat
    system: no
    shell: /bin/bash
    createhome: yes
    home: "{{tomcat_path}}"

- name: Change own directory tomcat
  file:
    path: "{{tomcat_path}}"
    state: directory
    owner: root

- name: Downloading required tomcat
  get_url:
    url: "{{tomcat_url}}"
    dest: /opt

- name: Extracting downloaded tomcat
  unarchive:
    src: "/opt/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: Renaming tomcat home
  shell: mv /opt/apache-tomcat-{{req_tomcat_ver}}/* {{tomcat_path}}

- name: Change mode recurse conf
  file:
    path: "{{tomcat_path}}/conf"
    state: directory
    recurse: yes
    mode: g+r

- name: Change mode conf
  file:
    path: "{{tomcat_path}}/conf"
    state: directory
    mode: g+x

- name: Change group directory tomcat
  file:
    path: "{{tomcat_path}}/{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: tomcat
  loop:
    - lib
    - conf
    - bin

- name: Change group file tomcat
  file:
    path: "{{tomcat_path}}/{{ item }}"
    state: file
    owner: root
    group: tomcat
  loop:
    - BUILDING.txt
    - CONTRIBUTING.md
    - LICENSE
    - NOTICE
    - README.md
    - RELEASE-NOTES
    - RUNNING.txt

- name: Create setenv.sh
  template:
    src: setenv
    dest: "{{tomcat_path}}/bin/setenv.sh"

- name: Change group setenv.sh
  file:
    path: "{{tomcat_path}}/bin/setenv.sh"
    state: file
    owner: root
    group: tomcat
    mode: g+x

- name: Change context.xml
  template:
    src: tomcat_context.xml
    dest: "{{tomcat_path}}/conf/context.xml"

- name: Configure tomcat.service
  template:
    src: tomcat.service
    dest: "/etc/systemd/system/"

- name: Reload service
  systemd:
    daemon_reload: yes

- name: Start Tomcat service
  systemd:
    name: tomcat
    enabled: yes
    masked: no

- name: Configure Tomcat users
  template:
    src: tomcat-users.xml
    dest: '{{tomcat_path}}/conf/tomcat-users.xml'

- name: Change tomcat port
  template:
    src: server.xml
    dest: '{{tomcat_path}}/conf/server.xml'

- name: Change manager context
  template:
    src: context_stock.xml
    dest: '{{tomcat_path}}/webapps/manager/META-INF/context.xml'

- name: Change host-manager context
  template:
    src: context_host.xml
    dest: '{{tomcat_path}}/webapps/host-manager/META-INF/context.xml'

- name: Tomcat /webapps ...
  file:
    path: "{{tomcat_path}}/{{ item }}"
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat
  loop:
    - webapps
    - work
    - temp
    - logs
